name: parrot_number
description: A simple guessing game built using Flutter.

version: 1.0.0+1

environment:
  flutter: '>=3.7.8'
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  share_plus: ^6.3.2

dev_dependencies:
  flutter_lints: ^2.0.1
  dependency_validator: ^3.2.2
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/parrot.jpg'
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: 'assets/parrot.jpg'

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: TATFont
      fonts:
        - asset: assets/fonts/GenSenRounded-R.ttc
          weight: 400
        - asset: assets/fonts/GenSenRounded-B.ttc
          weight: 700
